name: Project Checks

on:
  push:
    branches: [ working ]
  pull_request:
    branches: [ working ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '12.x', '14.x', '16.x' ]
    name: build-${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Install
        run: npm ci --no-optional
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build --if-present

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    name: test-${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Upgrade NPM
      run: npm install -g npm
    - name: Install
      run: npm ci
    - name: Run Tests
      run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: test-${{ matrix.node-version }}
        path-to-lcov: coverage/lcov.info
        parallel: true
  
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
        parallel-finished: true
